_target_: src.models.Siamese_module.SiameseModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

# net:
#   _target_: src.models.components.simple_dense_net.SimpleDenseNet
#   input_size: 784
#   lin1_size: 64
#   lin2_size: 128
#   lin3_size: 64
#   output_size: 10

multi_view_net:
  _target_: src.models.components.mvtn.MVTN
  nb_views: 8
  views_config: circular
  canonical_elevation: 30.0
  canonical_distance: 2.2 
  transform_distance: false
  input_view_noise: 0.0 
  shape_extractor: PointNet
  screatch_feature_extractor: true

multi_view_renderer:
  _target_: src.models.components.renderer.MVRenderer
  nb_views: 8
  image_size: 224
  pc_rendering: false
  object_color: blue
  background_color: white
  light_direction : "random"
  cull_backfaces : false
  points_radius : 0.006 
  points_per_pixel : 1 
  faces_per_pixel : 2

mvnet_depth: 18

