# @package _global_

defaults:
  - _self_
  - datamodule: shrec13.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: siamese.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/SharedData/Vinit/logs/Siamese_basemodel_debug_of_1/checkpoints/epoch=19-step=60.ckpt
